#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# build_project.tcl: Tcl script for re-creating project 'noc_router'
#
# Generated by Vivado on Tue May 11 12:20:29 +0200 2021
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_config.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/AXI_network_adapter_config.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_functions.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/component_declarations.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_interface_module.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/FIFO_buffer_module.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/buffer_decoder_module.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_branch.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/crossbar_mux_module.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/crossbar.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/arbiter.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/noc_router.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/AXI_to_noc_FIFO_buffer.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_to_AXI_FIFO_buffer.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_AXI_handshake_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_AXI_handshake_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_buffer_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_buffer_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_flow.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_flow.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_injector.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_receiver.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_req_AXI_handshake_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_resp_AXI_handshake_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_req_buffer_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_resp_buffer_controller.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_interface_module_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_interface_module_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_interface_interaction_2_routers_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_interface_interaction_2_routers_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/FIFO_buffer_module_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/FIFO_buffer_module_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/buffer_decoder_module_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/buffer_decoder_module_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/integration_1_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/integration_1_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_branch_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_branch_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_branch_cascade_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_branch_cascade_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/crossbar_mux_module_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/crossbar_mux_module_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/crossbar_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/crossbar_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/arbiter_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/arbiter_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_router_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_router_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_mesh_2x2_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_mesh_2x2_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/AXI_to_noc_FIFO_buffer_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/AXI_to_noc_FIFO_buffer_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_to_AXI_FIFO_buffer_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_to_AXI_FIFO_buffer_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_AXI_handshake_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_AXI_handshake_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_AXI_handshake_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_AXI_handshake_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_buffer_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_buffer_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_buffer_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_buffer_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_flow_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_flow_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_flow_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_flow_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_req_AXI_handshake_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_req_AXI_handshake_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_resp_AXI_handshake_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_resp_AXI_handshake_controller_tb.wcfg"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_resp_buffer_controller_tb.vhd"
#    "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_resp_buffer_controller_tb.wcfg"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_config.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/AXI_network_adapter_config.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_functions.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/component_declarations.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_interface_module.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/FIFO_buffer_module.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/buffer_decoder_module.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/router_branch.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/crossbar_mux_module.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/crossbar.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/arbiter.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/noc_router/noc_router.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/AXI_to_noc_FIFO_buffer.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_to_AXI_FIFO_buffer.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_AXI_handshake_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_AXI_handshake_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_buffer_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_buffer_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_req_flow.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/MNA_resp_flow.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_injector.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/noc_receiver.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_req_AXI_handshake_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_resp_AXI_handshake_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_req_buffer_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/design_sources/AXI_network_adapter/SNA_resp_buffer_controller.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_interface_module_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_interface_module_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_interface_interaction_2_routers_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_interface_interaction_2_routers_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/FIFO_buffer_module_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/FIFO_buffer_module_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/buffer_decoder_module_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/buffer_decoder_module_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/integration_1_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/integration_1_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_branch_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_branch_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/router_branch_cascade_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/router_branch_cascade_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/crossbar_mux_module_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/crossbar_mux_module_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/crossbar_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/crossbar_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/arbiter_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/arbiter_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_router_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_router_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_mesh_2x2_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_mesh_2x2_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/AXI_to_noc_FIFO_buffer_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/AXI_to_noc_FIFO_buffer_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/noc_to_AXI_FIFO_buffer_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/noc_to_AXI_FIFO_buffer_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_AXI_handshake_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_AXI_handshake_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_AXI_handshake_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_AXI_handshake_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_buffer_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_buffer_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_buffer_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_buffer_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_req_flow_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_req_flow_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/MNA_resp_flow_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/MNA_resp_flow_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_req_AXI_handshake_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_req_AXI_handshake_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_resp_AXI_handshake_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_resp_AXI_handshake_controller_tb.wcfg" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_sources/SNA_resp_buffer_controller_tb.vhd" \
   "C:/diplomski_rad/diplomski_rad-mrkovic_i_ramljak/vivado_project/simulation_wcfg/SNA_resp_buffer_controller_tb.wcfg" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "noc_router"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "build_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../Vivado/noc_router"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
# create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z045ffg900-2
create_project ${_xil_proj_name_} C:/Vivado/${_xil_proj_name_} -part xc7z045ffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:zc706:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zc706" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "343" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/design_sources/noc_router/router_config.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/AXI_network_adapter_config.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/router_functions.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/component_declarations.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/router_interface_module.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/FIFO_buffer_module.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/buffer_decoder_module.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/router_branch.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/crossbar_mux_module.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/crossbar.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/arbiter.vhd"] \
 [file normalize "${origin_dir}/design_sources/noc_router/noc_router.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/AXI_to_noc_FIFO_buffer.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/noc_to_AXI_FIFO_buffer.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_req_AXI_handshake_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_resp_AXI_handshake_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_req_buffer_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_resp_buffer_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_req_flow.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/MNA_resp_flow.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/noc_injector.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/noc_receiver.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/SNA_req_AXI_handshake_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/SNA_resp_AXI_handshake_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/SNA_req_buffer_controller.vhd"] \
 [file normalize "${origin_dir}/design_sources/AXI_network_adapter/SNA_resp_buffer_controller.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/design_sources/noc_router/router_config.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "noc_lib" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/AXI_network_adapter_config.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "noc_lib" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/router_functions.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "noc_lib" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/component_declarations.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "noc_lib" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/router_interface_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/FIFO_buffer_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/buffer_decoder_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/router_branch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/crossbar_mux_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/crossbar.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/arbiter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/noc_router/noc_router.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/AXI_to_noc_FIFO_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/noc_to_AXI_FIFO_buffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_req_AXI_handshake_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_resp_AXI_handshake_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_req_buffer_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_resp_buffer_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_req_flow.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/MNA_resp_flow.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/noc_injector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/noc_receiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/SNA_req_AXI_handshake_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/SNA_resp_AXI_handshake_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/SNA_req_buffer_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/design_sources/AXI_network_adapter/SNA_resp_buffer_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "noc_router" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj

# Create 'router_interface_module_sim' fileset (if not found)
if {[string equal [get_filesets -quiet router_interface_module_sim] ""]} {
  create_fileset -simset router_interface_module_sim
}

# Set 'router_interface_module_sim' fileset object
set obj [get_filesets router_interface_module_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/router_interface_module_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/router_interface_module_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'router_interface_module_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/router_interface_module_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets router_interface_module_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'router_interface_module_sim' fileset file properties for local files
# None

# Set 'router_interface_module_sim' fileset properties
set obj [get_filesets router_interface_module_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "router_interface_module_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'router_interface_interaction_2_routers_sim' fileset (if not found)
if {[string equal [get_filesets -quiet router_interface_interaction_2_routers_sim] ""]} {
  create_fileset -simset router_interface_interaction_2_routers_sim
}

# Set 'router_interface_interaction_2_routers_sim' fileset object
set obj [get_filesets router_interface_interaction_2_routers_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/router_interface_interaction_2_routers_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/router_interface_interaction_2_routers_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'router_interface_interaction_2_routers_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/router_interface_interaction_2_routers_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets router_interface_interaction_2_routers_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'router_interface_interaction_2_routers_sim' fileset file properties for local files
# None

# Set 'router_interface_interaction_2_routers_sim' fileset properties
set obj [get_filesets router_interface_interaction_2_routers_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "router_interface_interaction_2_routers_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'FIFO_buffer_module_sim' fileset (if not found)
if {[string equal [get_filesets -quiet FIFO_buffer_module_sim] ""]} {
  create_fileset -simset FIFO_buffer_module_sim
}

# Set 'FIFO_buffer_module_sim' fileset object
set obj [get_filesets FIFO_buffer_module_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/FIFO_buffer_module_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/FIFO_buffer_module_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'FIFO_buffer_module_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/FIFO_buffer_module_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets FIFO_buffer_module_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'FIFO_buffer_module_sim' fileset file properties for local files
# None

# Set 'FIFO_buffer_module_sim' fileset properties
set obj [get_filesets FIFO_buffer_module_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "FIFO_buffer_module_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'buffer_decoder_module_sim' fileset (if not found)
if {[string equal [get_filesets -quiet buffer_decoder_module_sim] ""]} {
  create_fileset -simset buffer_decoder_module_sim
}

# Set 'buffer_decoder_module_sim' fileset object
set obj [get_filesets buffer_decoder_module_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/buffer_decoder_module_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/buffer_decoder_module_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'buffer_decoder_module_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/buffer_decoder_module_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets buffer_decoder_module_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'buffer_decoder_module_sim' fileset file properties for local files
# None

# Set 'buffer_decoder_module_sim' fileset properties
set obj [get_filesets buffer_decoder_module_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "buffer_decoder_module_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'integration_1_sim' fileset (if not found)
if {[string equal [get_filesets -quiet integration_1_sim] ""]} {
  create_fileset -simset integration_1_sim
}

# Set 'integration_1_sim' fileset object
set obj [get_filesets integration_1_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/integration_1_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/integration_1_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'integration_1_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/integration_1_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets integration_1_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'integration_1_sim' fileset file properties for local files
# None

# Set 'integration_1_sim' fileset properties
set obj [get_filesets integration_1_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "integration_1_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'router_branch_sim' fileset (if not found)
if {[string equal [get_filesets -quiet router_branch_sim] ""]} {
  create_fileset -simset router_branch_sim
}

# Set 'router_branch_sim' fileset object
set obj [get_filesets router_branch_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/router_branch_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/router_branch_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'router_branch_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/router_branch_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets router_branch_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'router_branch_sim' fileset file properties for local files
# None

# Set 'router_branch_sim' fileset properties
set obj [get_filesets router_branch_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "router_branch_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'router_branch_cascade_sim' fileset (if not found)
if {[string equal [get_filesets -quiet router_branch_cascade_sim] ""]} {
  create_fileset -simset router_branch_cascade_sim
}

# Set 'router_branch_cascade_sim' fileset object
set obj [get_filesets router_branch_cascade_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/router_branch_cascade_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/router_branch_cascade_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'router_branch_cascade_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/router_branch_cascade_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets router_branch_cascade_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'router_branch_cascade_sim' fileset file properties for local files
# None

# Set 'router_branch_cascade_sim' fileset properties
set obj [get_filesets router_branch_cascade_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "router_branch_cascade_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'crossbar_mux_module_sim' fileset (if not found)
if {[string equal [get_filesets -quiet crossbar_mux_module_sim] ""]} {
  create_fileset -simset crossbar_mux_module_sim
}

# Set 'crossbar_mux_module_sim' fileset object
set obj [get_filesets crossbar_mux_module_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/crossbar_mux_module_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/crossbar_mux_module_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'crossbar_mux_module_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/crossbar_mux_module_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crossbar_mux_module_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'crossbar_mux_module_sim' fileset file properties for local files
# None

# Set 'crossbar_mux_module_sim' fileset properties
set obj [get_filesets crossbar_mux_module_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "crossbar_mux_module_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'crossbar_sim' fileset (if not found)
if {[string equal [get_filesets -quiet crossbar_sim] ""]} {
  create_fileset -simset crossbar_sim
}

# Set 'crossbar_sim' fileset object
set obj [get_filesets crossbar_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/crossbar_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/crossbar_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'crossbar_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/crossbar_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crossbar_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'crossbar_sim' fileset file properties for local files
# None

# Set 'crossbar_sim' fileset properties
set obj [get_filesets crossbar_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "crossbar_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'arbiter_sim' fileset (if not found)
if {[string equal [get_filesets -quiet arbiter_sim] ""]} {
  create_fileset -simset arbiter_sim
}

# Set 'arbiter_sim' fileset object
set obj [get_filesets arbiter_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/arbiter_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/arbiter_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'arbiter_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/arbiter_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets arbiter_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'arbiter_sim' fileset file properties for local files
# None

# Set 'arbiter_sim' fileset properties
set obj [get_filesets arbiter_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "arbiter_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'noc_router_sim' fileset (if not found)
if {[string equal [get_filesets -quiet noc_router_sim] ""]} {
  create_fileset -simset noc_router_sim
}

# Set 'noc_router_sim' fileset object
set obj [get_filesets noc_router_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/noc_router_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/noc_router_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'noc_router_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/noc_router_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets noc_router_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'noc_router_sim' fileset file properties for local files
# None

# Set 'noc_router_sim' fileset properties
set obj [get_filesets noc_router_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "noc_router_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'noc_mesh_2x2_sim' fileset (if not found)
if {[string equal [get_filesets -quiet noc_mesh_2x2_sim] ""]} {
  create_fileset -simset noc_mesh_2x2_sim
}

# Set 'noc_mesh_2x2_sim' fileset object
set obj [get_filesets noc_mesh_2x2_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/noc_mesh_2x2_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/noc_mesh_2x2_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'noc_mesh_2x2_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/noc_mesh_2x2_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets noc_mesh_2x2_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'noc_mesh_2x2_sim' fileset file properties for local files
# None

# Set 'noc_mesh_2x2_sim' fileset properties
set obj [get_filesets noc_mesh_2x2_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "noc_mesh_2x2_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "20000ns" -objects $obj

# Create 'AXI_to_noc_FIFO_buffer_sim' fileset (if not found)
if {[string equal [get_filesets -quiet AXI_to_noc_FIFO_buffer_sim] ""]} {
  create_fileset -simset AXI_to_noc_FIFO_buffer_sim
}

# Set 'AXI_to_noc_FIFO_buffer_sim' fileset object
set obj [get_filesets AXI_to_noc_FIFO_buffer_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/AXI_to_noc_FIFO_buffer_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/AXI_to_noc_FIFO_buffer_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'AXI_to_noc_FIFO_buffer_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/AXI_to_noc_FIFO_buffer_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets AXI_to_noc_FIFO_buffer_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'AXI_to_noc_FIFO_buffer_sim' fileset file properties for local files
# None

# Set 'AXI_to_noc_FIFO_buffer_sim' fileset properties
set obj [get_filesets AXI_to_noc_FIFO_buffer_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "AXI_to_noc_FIFO_buffer_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "20000ns" -objects $obj

# Create 'noc_to_AXI_FIFO_buffer_sim' fileset (if not found)
if {[string equal [get_filesets -quiet noc_to_AXI_FIFO_buffer_sim] ""]} {
  create_fileset -simset noc_to_AXI_FIFO_buffer_sim
}

# Set 'noc_to_AXI_FIFO_buffer_sim' fileset object
set obj [get_filesets noc_to_AXI_FIFO_buffer_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/noc_to_AXI_FIFO_buffer_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/noc_to_AXI_FIFO_buffer_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'noc_to_AXI_FIFO_buffer_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/noc_to_AXI_FIFO_buffer_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets noc_to_AXI_FIFO_buffer_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'noc_to_AXI_FIFO_buffer_sim' fileset file properties for local files
# None

# Set 'noc_to_AXI_FIFO_buffer_sim' fileset properties
set obj [get_filesets noc_to_AXI_FIFO_buffer_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "noc_to_AXI_FIFO_buffer_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_req_AXI_handshake_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_req_AXI_handshake_controller_sim] ""]} {
  create_fileset -simset MNA_req_AXI_handshake_controller_sim
}

# Set 'MNA_req_AXI_handshake_controller_sim' fileset object
set obj [get_filesets MNA_req_AXI_handshake_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_req_AXI_handshake_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_req_AXI_handshake_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_req_AXI_handshake_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_req_AXI_handshake_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_req_AXI_handshake_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_req_AXI_handshake_controller_sim' fileset file properties for local files
# None

# Set 'MNA_req_AXI_handshake_controller_sim' fileset properties
set obj [get_filesets MNA_req_AXI_handshake_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_req_AXI_handshake_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_resp_AXI_handshake_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_resp_AXI_handshake_controller_sim] ""]} {
  create_fileset -simset MNA_resp_AXI_handshake_controller_sim
}

# Set 'MNA_resp_AXI_handshake_controller_sim' fileset object
set obj [get_filesets MNA_resp_AXI_handshake_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_resp_AXI_handshake_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_resp_AXI_handshake_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_resp_AXI_handshake_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_resp_AXI_handshake_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_resp_AXI_handshake_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_resp_AXI_handshake_controller_sim' fileset file properties for local files
# None

# Set 'MNA_resp_AXI_handshake_controller_sim' fileset properties
set obj [get_filesets MNA_resp_AXI_handshake_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_resp_AXI_handshake_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_req_buffer_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_req_buffer_controller_sim] ""]} {
  create_fileset -simset MNA_req_buffer_controller_sim
}

# Set 'MNA_req_buffer_controller_sim' fileset object
set obj [get_filesets MNA_req_buffer_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_req_buffer_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_req_buffer_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_req_buffer_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_req_buffer_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_req_buffer_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_req_buffer_controller_sim' fileset file properties for local files
# None

# Set 'MNA_req_buffer_controller_sim' fileset properties
set obj [get_filesets MNA_req_buffer_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_req_buffer_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_resp_buffer_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_resp_buffer_controller_sim] ""]} {
  create_fileset -simset MNA_resp_buffer_controller_sim
}

# Set 'MNA_resp_buffer_controller_sim' fileset object
set obj [get_filesets MNA_resp_buffer_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_resp_buffer_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_resp_buffer_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_resp_buffer_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_resp_buffer_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_resp_buffer_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_resp_buffer_controller_sim' fileset file properties for local files
# None

# Set 'MNA_resp_buffer_controller_sim' fileset properties
set obj [get_filesets MNA_resp_buffer_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_resp_buffer_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_req_flow_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_req_flow_sim] ""]} {
  create_fileset -simset MNA_req_flow_sim
}

# Set 'MNA_req_flow_sim' fileset object
set obj [get_filesets MNA_req_flow_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_req_flow_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_req_flow_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_req_flow_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_req_flow_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_req_flow_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_req_flow_sim' fileset file properties for local files
# None

# Set 'MNA_req_flow_sim' fileset properties
set obj [get_filesets MNA_req_flow_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_req_flow_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'MNA_resp_flow_sim' fileset (if not found)
if {[string equal [get_filesets -quiet MNA_resp_flow_sim] ""]} {
  create_fileset -simset MNA_resp_flow_sim
}

# Set 'MNA_resp_flow_sim' fileset object
set obj [get_filesets MNA_resp_flow_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/MNA_resp_flow_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/MNA_resp_flow_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'MNA_resp_flow_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/MNA_resp_flow_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets MNA_resp_flow_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'MNA_resp_flow_sim' fileset file properties for local files
# None

# Set 'MNA_resp_flow_sim' fileset properties
set obj [get_filesets MNA_resp_flow_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "MNA_resp_flow_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'SNA_req_AXI_handshake_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet SNA_req_AXI_handshake_controller_sim] ""]} {
  create_fileset -simset SNA_req_AXI_handshake_controller_sim
}

# Set 'SNA_req_AXI_handshake_controller_sim' fileset object
set obj [get_filesets SNA_req_AXI_handshake_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/SNA_req_AXI_handshake_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/SNA_req_AXI_handshake_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'SNA_req_AXI_handshake_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/SNA_req_AXI_handshake_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets SNA_req_AXI_handshake_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'SNA_req_AXI_handshake_controller_sim' fileset file properties for local files
# None

# Set 'SNA_req_AXI_handshake_controller_sim' fileset properties
set obj [get_filesets SNA_req_AXI_handshake_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "SNA_req_AXI_handshake_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'SNA_resp_AXI_handshake_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet SNA_resp_AXI_handshake_controller_sim] ""]} {
  create_fileset -simset SNA_resp_AXI_handshake_controller_sim
}

# Set 'SNA_resp_AXI_handshake_controller_sim' fileset object
set obj [get_filesets SNA_resp_AXI_handshake_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/SNA_resp_AXI_handshake_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/SNA_resp_AXI_handshake_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'SNA_resp_AXI_handshake_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/SNA_resp_AXI_handshake_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets SNA_resp_AXI_handshake_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'SNA_resp_AXI_handshake_controller_sim' fileset file properties for local files
# None

# Set 'SNA_resp_AXI_handshake_controller_sim' fileset properties
set obj [get_filesets SNA_resp_AXI_handshake_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "SNA_resp_AXI_handshake_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Create 'SNA_resp_buffer_controller_sim' fileset (if not found)
if {[string equal [get_filesets -quiet SNA_resp_buffer_controller_sim] ""]} {
  create_fileset -simset SNA_resp_buffer_controller_sim
}

# Set 'SNA_resp_buffer_controller_sim' fileset object
set obj [get_filesets SNA_resp_buffer_controller_sim]
set files [list \
 [file normalize "${origin_dir}/simulation_sources/SNA_resp_buffer_controller_tb.vhd"] \
 [file normalize "${origin_dir}/simulation_wcfg/SNA_resp_buffer_controller_tb.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'SNA_resp_buffer_controller_sim' fileset file properties for remote files
set file "$origin_dir/simulation_sources/SNA_resp_buffer_controller_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets SNA_resp_buffer_controller_sim] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'SNA_resp_buffer_controller_sim' fileset file properties for local files
# None

# Set 'SNA_resp_buffer_controller_sim' fileset properties
set obj [get_filesets SNA_resp_buffer_controller_sim]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "SNA_resp_buffer_controller_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "15000ns" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
